/**
 * sbackend-lb4
 * sbackend lb4
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: fedir.indutnyi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentsScopeFilter } from './commentsScopeFilter';


export interface CommentsIncludeFilterItems { 
    relation?: CommentsIncludeFilterItems.RelationEnum;
    scope?: CommentsScopeFilter;
}
export namespace CommentsIncludeFilterItems {
    export type RelationEnum = 'userprofile';
    export const RelationEnum = {
        Userprofile: 'userprofile' as RelationEnum
    };
}


