/**
 * sbackend-lb4
 * sbackend lb4
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: fedir.indutnyi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<Usercontacts, \'id\' | \'belongstouser\'>, schemaOptions: { title: \'NewContactsInUser\', exclude: [ \'id\', \'belongstouser\' ] })
 */
export interface NewContactsInUser { 
    name?: string;
    email?: string;
    telephone?: string;
    createdAt?: string;
    updatedAt?: string;
    registereduserid?: number;
}

