/**
 * sbackend-lb4
 * sbackend lb4
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: fedir.indutnyi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Plantemplates { 
    id?: number;
    settingsIndustry?: string;
    settingsCategory?: string;
    uom?: string;
    aboutVisitorsCustomersMonthlyCrowd?: string;
    aboutVisitorsCustomersMonthlyVisitors?: string;
    aboutVisitorsCustomersConversionToCustomer?: string;
    portfolio?: string;
    averageGrossProfitMargin?: string;
    averageNetProfitMargin?: string;
    seasonality?: string;
    trendAcceleration?: string;
    otherDiscounts?: string;
    otherCogs?: string;
    interfaceProcessFlag?: string;
    createdAt?: string;
    updatedAt?: string;
}

