/**
 * sbackend-lb4
 * sbackend lb4
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: fedir.indutnyi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserloginScopeFilter } from './userloginScopeFilter';


export interface UserloginIncludeFilterItems { 
    relation?: UserloginIncludeFilterItems.RelationEnum;
    scope?: UserloginScopeFilter;
}
export namespace UserloginIncludeFilterItems {
    export type RelationEnum = 'loginUserProfile';
    export const RelationEnum = {
        LoginUserProfile: 'loginUserProfile' as RelationEnum
    };
}


