/**
 * sbackend-lb4
 * sbackend lb4
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: fedir.indutnyi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserteamrelationScopeFilter { 
    offset?: number;
    limit?: number;
    skip?: number;
    order?: string | Array<string>;
    where?: { [key: string]: object; };
    fields?: any | Set<string>;
    include?: Array<{ [key: string]: object; }>;
}

