// make description more clear
export const TitlesDescription = {
  brand: 'bp.portfolio.brandRef',
  productName: 'bp.portfolio.productNameRef',
  costPrice: 'bp.portfolio.costPriceRef',
  price: 'bp.portfolio.priceRef',
  productMarkup: 'bp.portfolio.productMarkupRef',
  productMargin: 'bp.portfolio.productMarginRef',
  eachNCustomerBuys: 'bp.portfolio.eachNCustomerBuysRef',
  absoluteCountValues: 'bp.portfolio.absoluteCountValuesRef',
  shareCustomerThatBuy:'bp.portfolio.shareCustomerThatBuyRef',
  monthlyCustomers:'bp.portfolio.monthlyCustomersRef',
  itemsPerOrder:'bp.portfolio.itemsPerOrderRef',
  ordersMonthPerCustomer: 'bp.portfolio.ordersMonthPerCustomerRef',
  totalUnits: 'bp.portfolio.totalUnitsRef',
  estimatedFailedOrders: 'bp.portfolio.estimatedFailedOrdersRef',
  standardDiscount: 'bp.portfolio.standardDiscountRef',
  //future work needed below
  onFirstInitialStock: 'bp.portfolio.onFirstInitialStockRef',
  totalAssetValue: 'bp.portfolio.totalAssetValueRef',
  beginningMonths: 'bp.portfolio.beginningMonthsRef',
  yearlyInflationRate: 'bp.portfolio.yearlyInflationRateRef',
  yearlyPriceIncrease: 'bp.portfolio.yearlyPriceIncreaseRef',
  UOM: 'bp.portfolio.UOMRef',
  totalMonthlyValue: 'bp.portfolio.totalMonthlyValueRef',
  overrideFromBusinessDetails: 'bp.portfolio.overrideFromBusinessDetailsRef',
  numberOfMonthsForInitialStock: 'bp.portfolio.numberOfMonthsForInitialStockRef',
  ammortisationOrDepreciation: 'bp.portfolio.ammortisationOrDepreciationRef',
}
