export const TitlesDescription = {
    disclaimer: 'bp.importantDisclaimer.sectionDescription',
    details: 'bp.details.sectionDescription',
    visitorsCustomers: 'bp.visitorsCustomers.sectionDescription',
    portfolio: 'bp.portfolio.sectionDescription',
    advancedInflationSettings: 'bp.advancedInflationSettings.sectionDescription',
    costPrice: 'bp.costPrice.sectionDescription',
    prices: 'bp.prices.sectionDescription',
    seasonality: 'bp.seasonality.sectionDescription',
    acceleration: 'bp.acceleration.sectionDescription',
    headcount: 'bp.headcount.sectionDescription',
    crowdTargetedAudience: 'bp.crowd_customers.crowdTargetedAudience.sectionDescription',
    visitors: 'bp.crowd_customers.visitors.sectionDescription',
    customers: 'bp.crowd_customers.customers.sectionDescription',
    volume: 'bp.volume.sectionDescription',
    discountsAndReturns: 'bp.discountsAndReturns.sectionDescription',
    netSales: 'bp.netSales.sectionDescription',
    otherCogs: 'bp.otherCogs.sectionDescription',
    grossMargin: 'bp.grossMargin.sectionDescription',
    investmentAndCapex: 'bp.investmentAndCapex.sectionDescription',
    marketing: 'bp.marketing.sectionDescription',
    opex: 'bp.opex.sectionDescription',
    rnd: 'bp.rnd.sectionDescription',
    otherincomeloss: 'bp.otherincomeloss.sectionDescription',
    ebidta: 'bp.ebidta.sectionDescription',
    investmentsRequired: 'bp.investmentsRequired.sectionDescription',

    churnAttrition: `This section allows to make an assumptions about Churn/Attrition. It means we can make an estimation of how many % of existing customers stop or exit from buying our services due to various reasons.`,
    capex: `Below data - represents Capital Expenditures, which is full list of investments for your business - such us buying land, house, equipment, fllet and machinery, cimputers, initial stock, initial rent deposit, and more.`,
}

