/**
 * sbackend-lb4
 * sbackend lb4
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: fedir.indutnyi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: @loopback/repository-json-schema#Optional<Omit<Comments, \'id\'>, \'userprofileId\'>, schemaOptions: { title: \'NewCommentsInUser\', exclude: [ \'id\' ], optional: [ \'userprofileId\' ] })
 */
export interface NewCommentsInUser { 
    commenttext?: string | null;
    ideaid?: number;
    commentdatetime?: string;
    isNotificationSent?: boolean | null;
    isdeleted?: number | null;
    interfaceProcessFlag?: string;
    feedbackrank?: number;
    createdAt?: string;
    updatedAt?: string;
    userprofileId?: number;
}

