export const glossaryDataDescription: any[] = [
  {
    Indicator: 'bp.importantDisclaimer.productsPortfoliooo',
    Formula: 'bp.importantDisclaimer.productsPortfolioFormula',
    Description: 'bp.importantDisclaimer.productsPortfolioDescription',
    References: 'bp.importantDisclaimer.productsPortfolioReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.inflation',
    Formula: 'bp.importantDisclaimer.inflationFormula',
    Description: 'bp.importantDisclaimer.inflationDescription',
    References: 'bp.importantDisclaimer.inflationReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.priceIncrease',
    Formula: 'bp.importantDisclaimer.priceIncreaseFormula',
    Description: 'bp.importantDisclaimer.priceIncreaseDescription',
    References: 'bp.importantDisclaimer.priceIncreaseReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.salaryIncrease',
    Formula: 'bp.importantDisclaimer.salaryIncreaseFormula',
    Description: 'bp.importantDisclaimer.salaryIncreaseDescription',
    References: 'bp.importantDisclaimer.salaryIncreaseReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.yearlyAssumptionsOfMultipliersForEconomyExpectations',
    Formula: 'bp.importantDisclaimer.yearlyAssumptionsOfMultipliersForEconomyExpectationsFormula',
    Description: 'bp.importantDisclaimer.yearlyAssumptionsOfMultipliersForEconomyExpectationsDescription',
    References: 'bp.importantDisclaimer.yearlyAssumptionsOfMultipliersForEconomyExpectationsReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.vatTax',
    Formula: 'bp.importantDisclaimer.vatTaxFormula',
    Description: 'bp.importantDisclaimer.vatTaxDescription',
    References: 'bp.importantDisclaimer.vatTaxReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.pricelistExcludingVat',
    Formula: 'bp.importantDisclaimer.pricelistExcludingVatFormula',
    Description: 'bp.importantDisclaimer.pricelistExcludingVatDescription',
    References: 'bp.importantDisclaimer.pricelistExcludingVatReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.costlistExcludingVat',
    Formula: 'bp.importantDisclaimer.costlistExcludingVatFormula',
    Description: 'bp.importantDisclaimer.costlistExcludingVatDescription',
    References: 'bp.importantDisclaimer.costlistExcludingVatReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.seasonality',
    Formula: 'bp.importantDisclaimer.seasonalityFormula',
    Description: 'bp.importantDisclaimer.seasonalityDescription',
    References: 'bp.importantDisclaimer.seasonalityReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.businessRumpUpOrAccelerationCurve',
    Formula: 'bp.importantDisclaimer.businessRumpUpOrAccelerationCurveFormula',
    Description: 'bp.importantDisclaimer.businessRumpUpOrAccelerationCurveDescription',
    References: 'bp.importantDisclaimer.businessRumpUpOrAccelerationCurveReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.targetedAudienceCrowd',
    Formula: 'bp.importantDisclaimer.targetedAudienceCrowdFormula',
    Description: 'bp.importantDisclaimer.targetedAudienceCrowdDescription',
    References: 'bp.importantDisclaimer.targetedAudienceCrowdReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.visitorsUsers',
    Formula: 'bp.importantDisclaimer.visitorsUsersFormula',
    Description: 'bp.importantDisclaimer.visitorsUsersDescription',
    References: 'bp.importantDisclaimer.visitorsUsersReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.customers',
    Formula: 'bp.importantDisclaimer.customersFormula',
    Description: 'bp.importantDisclaimer.customersDescription',
    References: 'bp.importantDisclaimer.customersReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.churnAttritionRate',
    Formula: 'bp.importantDisclaimer.churnAttritionRateFormula',
    Description: 'bp.importantDisclaimer.churnAttritionRateDescription',
    References: 'bp.importantDisclaimer.churnAttritionRateReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.clientbaseNewCustomers',
    Formula: 'bp.importantDisclaimer.clientbaseNewCustomersFormula',
    Description: 'bp.importantDisclaimer.clientbaseNewCustomersDescription',
    References: 'bp.importantDisclaimer.clientbaseNewCustomersReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.clientbaseLostCustomers',
    Formula: 'bp.importantDisclaimer.clientbaseLostCustomersFormula',
    Description: 'bp.importantDisclaimer.clientbaseLostCustomersDescription',
    References: 'bp.importantDisclaimer.clientbaseLostCustomersReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.clientbaseLoyalCustomers',
    Formula: 'bp.importantDisclaimer.clientbaseLoyalCustomersFormula',
    Description: 'bp.importantDisclaimer.clientbaseLoyalCustomersDescription',
    References: 'bp.importantDisclaimer.clientbaseLoyalCustomersReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.monthlyVolume',
    Formula: 'bp.importantDisclaimer.monthlyVolumeFormula',
    Description: 'bp.importantDisclaimer.monthlyVolumeDescription',
    References: 'bp.importantDisclaimer.monthlyVolumeReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.monthlyFreeGoods',
    Formula: 'bp.importantDisclaimer.monthlyFreeGoodsFormula',
    Description: 'bp.importantDisclaimer.monthlyFreeGoodsDescription',
    References: 'bp.importantDisclaimer.monthlyFreeGoodsReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.grossSalesRevenue',
    Formula: 'bp.importantDisclaimer.grossSalesRevenueFormula',
    Description: 'bp.importantDisclaimer.grossSalesRevenueDescription',
    References: 'bp.importantDisclaimer.grossSalesRevenueReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.discounts',
    Formula: 'bp.importantDisclaimer.discountsFormula',
    Description: 'bp.importantDisclaimer.discountsDescription',
    References: 'bp.importantDisclaimer.discountsReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.returns',
    Formula: 'bp.importantDisclaimer.returnsFormula',
    Description: 'bp.importantDisclaimer.returnsDescription',
    References: 'bp.importantDisclaimer.returnsReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.netSales',
    Formula: 'bp.importantDisclaimer.netSalesFormula',
    Description: 'bp.importantDisclaimer.netSalesDescription',
    References: 'bp.importantDisclaimer.netSalesReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.standardCogs',
    Formula: 'bp.importantDisclaimer.standardCogsFormula',
    Description: 'bp.importantDisclaimer.standardCogsDescription',
    References: 'bp.importantDisclaimer.standardCogsReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.otherCogs',
    Formula: 'bp.importantDisclaimer.otherCogsFormula',
    Description: 'bp.importantDisclaimer.otherCogsDescription',
    References: 'bp.importantDisclaimer.otherCogsReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.grossProfit',
    Formula: 'bp.importantDisclaimer.grossProfitFormula',
    Description: 'bp.importantDisclaimer.grossProfitDescription',
    References: 'bp.importantDisclaimer.grossProfitReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.grossProfitMargin',
    Formula: 'bp.importantDisclaimer.grossProfitMarginFormula',
    Description: 'bp.importantDisclaimer.grossProfitMarginDescription',
    References: 'bp.importantDisclaimer.grossProfitMarginReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.advertisingPromoMarketing',
    Formula: 'bp.importantDisclaimer.advertisingPromoMarketingFormula',
    Description: 'bp.importantDisclaimer.advertisingPromoMarketingDescription',
    References: 'bp.importantDisclaimer.advertisingPromoMarketingReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.monthlyNumberOfEmployees',
    Formula: 'bp.importantDisclaimer.monthlyNumberOfEmployeesFormula',
    Description: 'bp.importantDisclaimer.monthlyNumberOfEmployeesDescription',
    References: 'bp.importantDisclaimer.monthlyNumberOfEmployeesReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.grossSalary',
    Formula: 'bp.importantDisclaimer.grossSalaryFormula',
    Description: 'bp.importantDisclaimer.grossSalaryDescription',
    References: 'bp.importantDisclaimer.grossSalaryReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.netSalary',
    Formula: 'bp.importantDisclaimer.netSalaryFormula',
    Description: 'bp.importantDisclaimer.netSalaryDescription',
    References: 'bp.importantDisclaimer.netSalaryReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.netSalaryExpenses',
    Formula: 'bp.importantDisclaimer.netSalaryExpensesFormula',
    Description: 'bp.importantDisclaimer.netSalaryExpensesDescription',
    References: 'bp.importantDisclaimer.netSalaryExpensesReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.recruitmentCostExpense',
    Formula: 'bp.importantDisclaimer.recruitmentCostExpenseFormula',
    Description: 'bp.importantDisclaimer.recruitmentCostExpenseDescription',
    References: 'bp.importantDisclaimer.recruitmentCostExpenseReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.salaryTaxExpense',
    Formula: 'bp.importantDisclaimer.salaryTaxExpenseFormula',
    Description: 'bp.importantDisclaimer.salaryTaxExpenseDescription',
    References: 'bp.importantDisclaimer.salaryTaxExpenseReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.extraPayExpense',
    Formula: 'bp.importantDisclaimer.extraPayExpenseFormula',
    Description: 'bp.importantDisclaimer.extraPayExpenseDescription',
    References: 'bp.importantDisclaimer.extraPayExpenseReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.headcountExpenses',
    Formula: 'bp.importantDisclaimer.headcountExpensesFormula',
    Description: 'bp.importantDisclaimer.headcountExpensesDescription',
    References: 'bp.importantDisclaimer.headcountExpensesReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.opex',
    Formula: 'bp.importantDisclaimer.opexFormula',
    Description: 'bp.importantDisclaimer.opexDescription',
    References: 'bp.importantDisclaimer.opexReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.otherIncomeLoss',
    Formula: 'bp.importantDisclaimer.otherIncomeLossFormula',
    Description: 'bp.importantDisclaimer.otherIncomeLossDescription',
    References: 'bp.importantDisclaimer.otherIncomeLossReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.rAndD',
    Formula: 'bp.importantDisclaimer.rAndDFormula',
    Description: 'bp.importantDisclaimer.rAndDDescription',
    References: 'bp.importantDisclaimer.rAndDReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.ebidta',
    Formula: 'bp.importantDisclaimer.ebidtaFormula',
    Description: 'bp.importantDisclaimer.ebidtaDescription',
    References: 'bp.importantDisclaimer.ebidtaReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.capexInvestmentsAcquisitionsOfFixedAssets',
    Formula: 'bp.importantDisclaimer.capexInvestmentsAcquisitionsOfFixedAssetsFormula',
    Description: 'bp.importantDisclaimer.capexInvestmentsAcquisitionsOfFixedAssetsDescription',
    References: 'bp.importantDisclaimer.capexInvestmentsAcquisitionsOfFixedAssetsReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.amortizationAndDepreciation',
    Formula: 'bp.importantDisclaimer.amortizationAndDepreciationFormula',
    Description: 'bp.importantDisclaimer.amortizationAndDepreciationDescription',
    References: 'bp.importantDisclaimer.amortizationAndDepreciationReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.ebitOperatingProfit',
    Formula: 'bp.importantDisclaimer.ebitOperatingProfitFormula',
    Description: 'bp.importantDisclaimer.ebitOperatingProfitDescription',
    References: 'bp.importantDisclaimer.ebitOperatingProfitReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.profitTax',
    Formula: 'bp.importantDisclaimer.profitTaxFormula',
    Description: 'bp.importantDisclaimer.profitTaxDescription',
    References: 'bp.importantDisclaimer.profitTaxReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.loanAndInterest',
    Formula: 'bp.importantDisclaimer.loanAndInterestFormula',
    Description: 'bp.importantDisclaimer.loanAndInterestDescription',
    References: 'bp.importantDisclaimer.loanAndInterestReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.netIncome',
    Formula: 'bp.importantDisclaimer.netIncomeFormula',
    Description: 'bp.importantDisclaimer.netIncomeDescription',
    References: 'bp.importantDisclaimer.netIncomeReferences',
  },
  {
    Indicator: 'bp.importantDisclaimer.totalInvestmentRequired',
    Formula: 'bp.importantDisclaimer.totalInvestmentRequiredFormula',
    Description: 'bp.importantDisclaimer.totalInvestmentRequiredDescription',
    References: 'bp.importantDisclaimer.totalInvestmentRequiredReferences',
  },
];
