name: Super-Linter

on:
  push:
    branches:
      # - main
      - sandbox
      # - dev

# Global Branch Settings
env:
  BRANCH_CHANNEL_MAPPING_JSON: '{"main": "production", "sandbox": "sandbox", "dev": "dev", "tst": "tst"}'
  disableSuperLinterInTST: true
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: true

jobs:
  
  identify-branch-type:
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Type
        run: |
          BRANCH_TYPE=$(echo "$BRANCH_CHANNEL_MAPPING_JSON" | jq -r ".[\"${{ github.ref_name }}\"] // .[\"*\"] // \"tst\"")
          echo "BRANCH_TYPE=${BRANCH_TYPE}" >> $GITHUB_ENV
          echo "Branch Type identified as: $BRANCH_TYPE"

  Scan-Containers:
    needs: identify-branch-type
    # if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Branch Type
        run: |
          BRANCH_TYPE=$(echo "$BRANCH_CHANNEL_MAPPING_JSON" | jq -r ".[\"${{ github.ref_name }}\"] // .[\"*\"] // \"tst\"")
          echo "BRANCH_TYPE=${BRANCH_TYPE}" >> $GITHUB_ENV
          echo "Branch Type identified as: $BRANCH_TYPE"


      - name: Login to Container Registry
        run: echo ${{ secrets.GITLAB_REGISTRY_PASSWORD }} | docker login ${{ secrets.GITLAB_REGISTRY_URL }} -u ${{ secrets.GITLAB_REGISTRY_USERNAME }} --password-stdin

      # - name: Scan Builder Stage image
      #   uses: anchore/scan-action@v3
      #   with:
      #     image: "${{ secrets.GITLAB_REGISTRY_URL }}/splatforma/sfrontend:demo-github-builderstage"
      #     fail-build: false
      #     severity-cutoff: critical
      #     output-format: table

      - name: Scan Final Compiled Image
        uses: anchore/scan-action@v3
        with:
          image: "${{ secrets.GITLAB_REGISTRY_URL }}/splatforma/${{ github.event.repository.name }}:${{ env.BRANCH_TYPE }}-github"
          fail-build: false
          severity-cutoff: critical
          output-format: table

  newman-test:
    needs: [ identify-branch-type ]
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # - uses: matt-ball/newman-action@master
      #   with:
      #     # apiKey: "qgawieudhdcnlkzxmclkzxcklmdzlkfvmasdk;asdkf;gag" # ${{ secrets.postmanApiKey }}
      #     # Authorization: "Basic ZGVtbzpkZW1v"
      #     insecure: true
      #     envVar: '[{ "key": "baseUrl", "value": "https://app" }]'
      #     collection: "openapi/app.json"
      #     # environment: 5922408-228c7edd-fc15-4f68-9665-a35d7df6945b

  check-liveness-probe:
    needs: [ identify-branch-type]
    strategy:
      fail-fast: true    
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # - name: Make API request
      #   run: |
      #     API_URL="https://google.com"
      #     STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -k $API_URL)
      #     RESPONSE_BODY=$(curl -s -k $API_URL)
      #     if [ $STATUS_CODE -eq 200 ] && [ "$RESPONSE_BODY" == "true" ]; then
      #       echo "APP is alive!"
      #     else
      #       echo "APP is not responding properly. Status code: $STATUS_CODE, Response body: $RESPONSE_BODY"
      #       exit 1
      #     fi
